name: Build check

on:
  - pull_request
env:
  PKG_CACHE_PATH: /home/runner/work/kyvejs/kyvejs/.pkg-cache
jobs:
  build-check:
    runs-on: ubuntu-latest
    set:
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: install yarn
        run: npm install --global yarn
      - name: "setup"
        run: yarn setup
      - name: check dirs
        run: ls -a
      - name: check folder
        run: pwd
      - name: create pkg dir
        run: mkdir -p /home/runner/work/kyvejs/kyvejs/.pkg-cache/v3.4/
      - name: check dirs
        run: ls -a
      - name: "build:binaries"
        run: yarn build:binaries
