name: Build check

on:
  - pull_request
env:
  PKG_CACHE_PATH: /home/runner/work/kyvejs/kyvejs
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: install yarn
        run: npm install --global yarn
      - name: "setup"
        run: yarn setup
      - name: check dirs
        run: ls -a
      - name: check folder
        run: pwd
      - name: check dirs
        run: ls -a /home/runner/work/kyvejs/kyvejs/
      - name: "build:binaries"
        working-directory: .
        run: yarn build:binaries
