name: unit tests

on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      npm_config_user: "root"
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
      - name: "nodejs install"
        uses: actions/setup-node@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: install yarn
        run: npm install --global yarn
      - name: "setup"
        run: yarn setup
      - name: "test"
        run: yarn test
      - name: Cypress tests ✅
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
          "context": "unit tests",
          "state": "pending",
          "description": "Cypress tests passed",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'  
